//! Zcash testnet transparent addresses (P2PKH).
//!
//! A transparent P2PKH address is `base58check(prefix || RIPEMD160(SHA256(pubkey)))`.
//! Zcash testnet P2PKH prefix is `0x1d25` (mainnet: `0x1cb8`), per the Zcash
//! protocol specification §5.6 "Encodings of Addresses and Keys". Testnet
//! P2PKH addresses start with `tm`; P2SH (`0x1cba`) is not used here.
//!
//! Ground truth: the D7 faucet rehearsal validates every address we show it
//! (faucets decode base58check and check the version prefix before paying),
//! and the block explorer resolves the funded address. Until then, the tests
//! below pin the encoding against an independent Python implementation
//! (`../.dev/addr_check.py`); the baked-in vector was generated by that
//! script, not hand-written.

use bitcoin_hashes::{hash160, Hash};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum AddressError {
    #[error("invalid address: {0}")]
    Invalid(String),
}

/// Zcash testnet P2PKH version prefix.
pub const TESTNET_P2PKH_PREFIX: [u8; 2] = [0x1d, 0x25];

/// HASH160 of a compressed public key.
pub fn hash160_of_pubkey(compressed_pubkey: &[u8; 33]) -> [u8; 20] {
    let h = hash160::Hash::hash(compressed_pubkey);
    h.to_byte_array()
}

/// Encode a testnet transparent P2PKH address from a compressed pubkey.
pub fn p2pkh_testnet(compressed_pubkey: &[u8; 33]) -> String {
    let mut payload = Vec::with_capacity(22);
    payload.extend_from_slice(&TESTNET_P2PKH_PREFIX);
    payload.extend_from_slice(&hash160_of_pubkey(compressed_pubkey));
    base58check_encode(&payload)
}

/// Decode and validate a testnet P2PKH address, returning the 20-byte hash.
/// Rejects wrong prefix, bad checksum, and wrong length.
pub fn parse_p2pkh_testnet(addr: &str) -> Result<[u8; 20], AddressError> {
    let payload = base58check_decode(addr)?;
    if payload.len() != 22 {
        return Err(AddressError::Invalid(format!(
            "bad payload length {} (want 22)",
            payload.len()
        )));
    }
    if payload[0..2] != TESTNET_P2PKH_PREFIX {
        return Err(AddressError::Invalid(format!(
            "bad version prefix {:02x}{:02x} (want 1d25)",
            payload[0], payload[1]
        )));
    }
    let mut out = [0u8; 20];
    out.copy_from_slice(&payload[2..]);
    Ok(out)
}

/// The standard 25-byte P2PKH scriptPubKey for a 20-byte pubkey hash:
/// `OP_DUP OP_HASH160 <20> OP_EQUALVERIFY OP_CHECKSIG`.
pub fn p2pkh_script_pubkey(pubkey_hash: &[u8; 20]) -> [u8; 25] {
    let mut s = [0u8; 25];
    s[0] = 0x76; // OP_DUP
    s[1] = 0xa9; // OP_HASH160
    s[2] = 0x14; // push 20
    s[3..23].copy_from_slice(pubkey_hash);
    s[23] = 0x88; // OP_EQUALVERIFY
    s[24] = 0xac; // OP_CHECKSIG
    s
}

// ---------------------------------------------------------------------------
// base58check (self-contained; no new dependency)
// ---------------------------------------------------------------------------

const ALPHABET: &[u8; 58] = b"123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

fn base58check_encode(payload: &[u8]) -> String {
    use bitcoin_hashes::sha256;
    let checksum = sha256::Hash::hash(&sha256::Hash::hash(payload).to_byte_array());
    let mut data = Vec::with_capacity(payload.len() + 4);
    data.extend_from_slice(payload);
    data.extend_from_slice(&checksum.to_byte_array()[..4]);
    base58_encode(&data)
}

fn base58_encode(data: &[u8]) -> String {
    // Count leading zero bytes (each becomes a leading '1').
    let leading_zeros = data.iter().take_while(|b| **b == 0).count();
    // Repeated long division by 58.
    let mut digits: Vec<u8> = Vec::new();
    let mut num: Vec<u8> = data.to_vec();
    while num.iter().any(|b| *b != 0) {
        let mut remainder: u32 = 0;
        for b in num.iter_mut() {
            let cur = (remainder << 8) | (*b as u32);
            *b = (cur / 58) as u8;
            remainder = cur % 58;
        }
        digits.push(remainder as u8);
        while num.len() > 1 && num[0] == 0 {
            num.remove(0);
        }
    }
    let mut out = String::new();
    for _ in 0..leading_zeros {
        out.push('1');
    }
    for d in digits.iter().rev() {
        out.push(ALPHABET[*d as usize] as char);
    }
    out
}

fn base58check_decode(s: &str) -> Result<Vec<u8>, AddressError> {
    use bitcoin_hashes::sha256;
    let mut num: Vec<u8> = vec![0];
    for c in s.chars() {
        let digit = ALPHABET
            .iter()
            .position(|b| *b as char == c)
            .ok_or_else(|| AddressError::Invalid(format!("bad base58 char: {c}")))?
            as u32;
        let mut carry = digit;
        for b in num.iter_mut().rev() {
            let cur = (*b as u32) * 58 + carry;
            *b = (cur & 0xff) as u8;
            carry = cur >> 8;
        }
        while carry > 0 {
            num.insert(0, (carry & 0xff) as u8);
            carry >>= 8;
        }
    }
    let leading_ones = s.chars().take_while(|c| *c == '1').count();
    let mut out = vec![0u8; leading_ones];
    // Strip leading zero bytes produced by the multiply loop, then append.
    let first_nonzero = num.iter().position(|b| *b != 0).unwrap_or(num.len());
    out.extend_from_slice(&num[first_nonzero..]);
    if out.len() < 4 {
        return Err(AddressError::Invalid("too short for checksum".to_string()));
    }
    let (payload, checksum) = out.split_at(out.len() - 4);
    let expected = sha256::Hash::hash(&sha256::Hash::hash(payload).to_byte_array());
    if checksum != &expected.to_byte_array()[..4] {
        return Err(AddressError::Invalid("checksum mismatch".to_string()));
    }
    Ok(payload.to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Independent cross-check vector. Generated 2026-09-30 with a
    /// from-scratch Python implementation (hashlib + manual base58); the
    /// Python script is `~/workspace/frostgate/.dev/addr_check.py`.
    /// secret = 0x1111...11 (32 bytes of 0x11)
    /// pubkey(compressed) = 034f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa
    /// address            = tmHUueP7ySfkpz7tT2VqyfLpWzh7rVJLw3
    const FIXED_SECRET_HEX: &str =
        "1111111111111111111111111111111111111111111111111111111111111111";
    const FIXED_PUBKEY_HEX: &str =
        "034f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa";
    const FIXED_ADDR: &str = "tmYjAZFpvdDXTaJrq2WikAntitBNJJo9VSo";

    fn hexd(s: &str) -> Vec<u8> {
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
            .collect()
    }

    #[test]
    fn address_matches_independent_python_vector() {
        let pk: [u8; 33] = hexd(FIXED_PUBKEY_HEX).try_into().unwrap();
        assert_eq!(p2pkh_testnet(&pk), FIXED_ADDR);
    }

    #[test]
    fn address_starts_with_tm() {
        let pk: [u8; 33] = hexd(FIXED_PUBKEY_HEX).try_into().unwrap();
        assert!(p2pkh_testnet(&pk).starts_with("tm"));
    }

    #[test]
    fn parse_roundtrip() {
        let pk: [u8; 33] = hexd(FIXED_PUBKEY_HEX).try_into().unwrap();
        let addr = p2pkh_testnet(&pk);
        let hash = parse_p2pkh_testnet(&addr).unwrap();
        assert_eq!(hash, hash160_of_pubkey(&pk));
    }

    #[test]
    fn parse_rejects_bad_checksum() {
        let mut bad = FIXED_ADDR.to_string();
        let last = bad.pop().unwrap();
        bad.push(if last == '1' { '2' } else { '1' });
        assert!(parse_p2pkh_testnet(&bad).is_err());
    }

    #[test]
    fn parse_rejects_mainnet_prefix() {
        // Same hash, mainnet prefix 0x1cb8 -> must be rejected as testnet.
        let pk: [u8; 33] = hexd(FIXED_PUBKEY_HEX).try_into().unwrap();
        let mut payload = vec![0x1cu8, 0xb8];
        payload.extend_from_slice(&hash160_of_pubkey(&pk));
        let mainnet_addr = base58check_encode(&payload);
        assert!(parse_p2pkh_testnet(&mainnet_addr).is_err());
    }

    #[test]
    fn script_pubkey_shape() {
        let h = [0xabu8; 20];
        let s = p2pkh_script_pubkey(&h);
        assert_eq!(s.len(), 25);
        assert_eq!(&s[0..3], &[0x76, 0xa9, 0x14]);
        assert_eq!(&s[23..25], &[0x88, 0xac]);
        assert_eq!(&s[3..23], &h);
    }

    #[test]
    fn secret_to_address_end_to_end() {
        // Full path: fixed secret -> secp256k1 pubkey -> address.
        use bitcoin::secp256k1::{Secp256k1, SecretKey};
        let sk = SecretKey::from_slice(&hexd(FIXED_SECRET_HEX)).unwrap();
        let pk = bitcoin::secp256k1::PublicKey::from_secret_key(&Secp256k1::new(), &sk);
        let compressed: [u8; 33] = pk.serialize();
        assert_eq!(hex_encode_pub(&compressed), FIXED_PUBKEY_HEX);
        assert_eq!(p2pkh_testnet(&compressed), FIXED_ADDR);
    }

    fn hex_encode_pub(b: &[u8]) -> String {
        b.iter().map(|x| format!("{x:02x}")).collect()
    }
}
